# This file was generated by GoReleaser. DO NOT EDIT.
cask "ward" do
  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", staged_path.to_s]
  end

  version "0.1.17"

  on_macos do
    on_intel do
      sha256 "f0b5a98bf25c3f87092400b6b8f3059b570827dd43cf2b68d1b3cdea316078bb"
      url "https://github.com/oporpino/ward/releases/download/v#{version}/ward_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "2d77ab2f44f2439fa52465b327a0402fa8e7170913792d97cbce9fd66c7073dc"
      url "https://github.com/oporpino/ward/releases/download/v#{version}/ward_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "07ef3dd69c956f677367b957f585303f372ff2a03b4f4e800aa4765420bbc9df"
      url "https://github.com/oporpino/ward/releases/download/v#{version}/ward_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f159698f283f9bf237ea4aadd85f94a0dd866ccd2b38a7ad02f8fa4e0ee03424"
      url "https://github.com/oporpino/ward/releases/download/v#{version}/ward_linux_arm64.tar.gz"
    end
  end

  name "ward"
  desc "Hierarchical secrets management using SOPS+age."
  homepage "https://github.com/oporpino/ward"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ward"
  bash_completion "completions/ward.bash"
  fish_completion "completions/ward.fish"
  zsh_completion "completions/ward.zsh"

  # No zap stanza required

end
