# This file was generated by GoReleaser. DO NOT EDIT.
cask "ward" do
  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", staged_path.to_s]
  end

  version "0.1.24"

  on_macos do
    on_intel do
      sha256 "41f9feb27d954f6a587566f9a847da230e92f711ca1fd3e1ceed69e94c5c5087"
      url "https://github.com/oporpino/ward/releases/download/v#{version}/ward_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3244808d1c03ef398e5d07e2f75888407d4624416a08e8962a9df1dd8fc9e5d9"
      url "https://github.com/oporpino/ward/releases/download/v#{version}/ward_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ebfd3f09fa3d8de39e196221395609bb09b3cac6d94cdfc8ea83d965d45e6c75"
      url "https://github.com/oporpino/ward/releases/download/v#{version}/ward_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "dc9eecd2df190ba5a61ef146545c1642bbb679f3751d9a4eb87a1016cd808a6a"
      url "https://github.com/oporpino/ward/releases/download/v#{version}/ward_linux_arm64.tar.gz"
    end
  end

  name "ward"
  desc "Hierarchical secrets management using SOPS+age."
  homepage "https://github.com/oporpino/ward"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ward"
  bash_completion "completions/ward.bash"
  fish_completion "completions/ward.fish"
  zsh_completion "completions/ward.zsh"

  # No zap stanza required

end
