# This file was generated by GoReleaser. DO NOT EDIT.
cask "ward" do
  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", staged_path.to_s]
  end

  version "0.1.48"

  on_macos do
    on_intel do
      sha256 "8ea75b6fe21b2f77dbb819b11039a9936127bf398f37a9ab566e2f12948d0aac"
      url "https://github.com/br4zz4/ward/releases/download/v#{version}/ward_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "328fe40c1a744c7271595b2da805242bc3b83c9f93cba0cbb8e622de3436eb13"
      url "https://github.com/br4zz4/ward/releases/download/v#{version}/ward_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c949567631c50e6b8c06a3308fc50331491babc573bbd4951cff0625ee10a950"
      url "https://github.com/br4zz4/ward/releases/download/v#{version}/ward_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "0746e58c2fda31de3165054fbe388b9537b9071bd3bb36822cb3d4f0f355edd6"
      url "https://github.com/br4zz4/ward/releases/download/v#{version}/ward_linux_arm64.tar.gz"
    end
  end

  name "ward"
  desc "Hierarchical secrets manager"
  homepage "https://github.com/br4zz4/ward"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ward"
  bash_completion "completions/ward.bash"
  fish_completion "completions/ward.fish"
  zsh_completion "completions/ward.zsh"

  # No zap stanza required

end
